version: '3'

networks:
  nw_wapp_simple_notes:
  proxy_net:
    external:
      name: proxy_net

services:
  nginx:
    restart: always
    container_name: wapp_simple_notes_nginx
    # hostname: wapp_simple_notes.local
    image: wapp_simple_notes_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    # ports:
    #   - "${NGINX_PORT}:80"
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php_fpm
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - nw_wapp_simple_notes
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_net"
      - "traefik.http.routers.wapp_simple_notes.rule=Host(`${PREFIX}wapp_simple_notes.local`) || Host(`${PREFIX}wapp_simple_notes.localhost`)"

  php_fpm:
    restart: always
    container_name: wapp_simple_notes_php_fpm
    # hostname: php_fpm
    image: wapp_simple_notes_php_fpm
    build:
      context: ./docker/php-workspace
      dockerfile: ./Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    volumes:
      - ${WORK_PATH}:/var/www
      - ./docker/php-workspace/logs/log1:/var/log/
      - ./docker/php-workspace/logs/log2:/usr/local/var/log
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    env_file:
      - ./.env
    networks:
      - nw_wapp_simple_notes